packages:
  - docs
  - lib
catalog:
  '@commitlint/cli': ^19.7.1
  '@commitlint/config-conventional': ^19.7.1
  '@types/node': ^22.13.4
  '@vinicunca/eslint-config': ^3.0.0
  bumpp: ^10.0.3
  eslint: ^9.20.1
  lint-staged: ^15.4.3
  simple-git-hooks: ^2.11.1
  taze: ^18.5.0
  typescript: ^5.7.3
